
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Teste Flores</title>
    <link rel="stylesheet" href="<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="style.css">
    <head>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    </head>
    
</head>
<body>

    <header>

        <input type="checkbox" name="" id="toggler">
        <label for="toggler" class="fas fa-bars"></label>

        <a href="" class="logo">Flores<span>.</span></a>

        <nav class="navbar">
            <a href="#home">home</a>
            <a href="#about">Sobre</a>
            <a href="produtos.php">Produtos</a>
            <a href="#review">Avaliação</a>
            <a href="#contact">Contato</a>
        </nav>

        <div class="icons">
           <a href="verificacao.html" class="fas fa-sign-in-alt"></a>
           <a href="cadastro" class="fas fa-user-plus"></a>
        </div>
    </header>

    <section class="home" id="home">

        <div class="content">
            <h3>Flores frescas</h3>
            <span>Flores naturais & cheirosas</span>
            <p>Lorem ipsum dolor sit amet consectetur adipiscing elit. Beatae laborum ut minus corrupti dolorum dolore assumenda iste voluptate dolorem pariatur.</p>
            <a href="produtos.php" class="btn">Compre agora</a>
        </div>

    </section>

    <section class="about" id="about">

         <h1 class="heading"> <span> Sobre </span> nós </h1>
         <div class="row">
        <div class="video-container">
           <video src="images/mulhercampo2.mp4" loop autoplay muted></video> 
           <h3>Melhores da região</h3>
        </div>

            <div class="content">
                <h3>Por que escolher nós?</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem cumque sit nemo 
                pariatur corporis perspiciatis aspernatur a ullam repudiandae autem asperiores 
                quibusdam omnis commodi alias repellat illum, unde optio temporibus.</p>
                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Accusantium ea est 
                commodi incidunt magni quia molestias perspiciatis, unde repudiandae quidem.</p>
                <a href="sabermais.php" class="btn">Saber mais</a>
            </div>
        </div>

    </section>

    <section class="icons-container">
        <div class="icons">
            <img src="images/delivery-trollery.png" width="80rem" alt="">
            <div class="info">
                <h3>Entrega grátis</h3>
                <span>Em todos os pedidos</span>
            </div>
        </div>

        <div class="icons">
            <img src="images/pagamento-em-dinheiro.png" width="80rem" alt="">
            <div class="info">
                <h3>Devolução em 10 dias</h3>
                <span>Garantia de devolução</span>
            </div>
        </div>

        <div class="icons">
            <img src="images/cartao-presente.png" width="80rem"  alt="">
            <div class="info">
                <h3>Ofertas e presentes</h3>
                <span>Acima de 5 pedidos</span>
            </div>
        </div>

        <div class="icons">
            <img src="images/cartao-de-credito.png" width="80rem" alt="">
            <div class="info">
                <h3>Pagamento seguro</h3>
                <span>Protegido pelo Paypal</span>
            </div>
        </div>
     </section>

        <section class="products" id="products">
            <h1 class="heading"> mais <span> vendidos </span> </h1>
            <div class="box-container">

                <div class="box">
                   <span class="discount">-10%</span> 
                   <div class="image">
                    <img src="images/fotoflor.png" alt="">
                        <div class="icons">
                            <a href="#" class="fas fa-heart"></a>
                            <a href="#" class="cart-btn">Adiconar ao carrinho</a>
                            <a href="#" class="fas fa-share"></a> 
                        </div>
                   </div>
                     <div class="content">
                        <h3>Jasmim</h3>
                    <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                      </div>
                </div>

                <div class="box">
                    <span class="discount">-15%</span> 
                    <div class="image">
                     <img src="images/flor.png" alt="" >
                         <div class="icons">
                             <a href="#" class="fas fa-heart"></a>
                             <a href="#" class="cart-btn">Adiconar ao carrinho</a>
                             <a href="#" class="fas fa-share"></a> 
                         </div>
                    </div>
                      <div class="content">
                         <h3>Orquidea</h3>
                     <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                       </div>
                 </div>

                 <div class="box">
                    <span class="discount">-5%</span> 
                    <div class="image">
                     <img src="images/flor1.png" alt="" >
                         <div class="icons">
                             <a href="#" class="fas fa-heart"></a>
                             <a href="#" class="cart-btn">Adicionar ao carrinho</a>
                             <a href="#" class="fas fa-share"></a> 
                         </div>
                    </div>
                      <div class="content">
                         <h3>Tília</h3>
                     <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                       </div>
                 </div>

                 <div class="box">
                    <span class="discount">-20%</span> 
                    <div class="image">
                     <img src="images/flor3.png" alt="">
                         <div class="icons">
                             <a href="#" class="fas fa-heart"></a>
                             <a href="#" class="cart-btn">Adicionar ao carrinho</a>
                             <a href="#" class="fas fa-share"></a> 
                         </div>
                    </div>
                      <div class="content">
                         <h3>Rosas</h3>
                     <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                       </div>
                 </div>

                 <div class="box">
                    <span class="discount">-17%</span> 
                    <div class="image">
                     <img src="images/flor2.png" alt="" >
                         <div class="icons">
                             <a href="#" class="fas fa-heart"></a>
                             <a href="#" class="cart-btn">Adicionar ao carrinho</a>
                             <a href="#" class="fas fa-share"></a> 
                         </div>
                    </div>
                      <div class="content">
                         <h3>Tulipas</h3>
                     <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                       </div>
                 </div>

                 <div class="box">
                    <span class="discount">-3%</span> 
                    <div class="image">
                     <img src="images/flor4.png" alt="">
                         <div class="icons">
                             <a href="#" class="fas fa-heart"></a>
                             <a href="#" class="cart-btn">adicionar ao carrinho</a>
                             <a href="#" class="fas fa-share"></a> 
                         </div>
                    </div>
                      <div class="content">
                         <h3>Girassol</h3>
                     <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                       </div>
                 </div>

                 <div class="box">
                    <span class="discount">-18%</span> 
                    <div class="image">
                     <img src="images/flor5.png" alt="">
                         <div class="icons">
                             <a href="#" class="fas fa-heart"></a>
                             <a href="#" class="cart-btn">Adicionar ao carrinho</a>
                             <a href="#" class="fas fa-share"></a> 
                         </div>
                    </div>
                      <div class="content">
                         <h3>Rosas brancas</h3>
                     <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                       </div>
                 </div>

                 <div class="box">
                    <span class="discount">-8%</span> 
                    <div class="image">
                     <img src="images/" alt="">
                         <div class="icons">
                             <a href="#" class="fas fa-heart"></a>
                             <a href="#" class="cart-btn">Adicionar ao carrinho</a>
                             <a href="#" class="fas fa-share"></a> 
                         </div>
                    </div>
                      <div class="content">
                         <h3>Margaridas</h3>
                     <div class="price"> R$12.99 <span> R$15.99 </span> </div>
                       </div>
                 </div>
            </div>

        </section>

        <section class="review" id="review">
           <h1 class="heading"> Avaliações dos <span> clientes </span> </h1>
           <div class="box-container">
                <div class="box">
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti asperiores
                        laboriosam praesentium enim maiores? Ad repellat voluptates alias facere repudiandae
                        dolor accusamus enim ut odit, aliquam nesciunt esque nulla dignissimos.</p>
                        <div class="user">
                            <img src="images/flor2.jpeg" alt="">
                            <div class="user-info">
                                <h3>john deo</h3>
                             
                            </div>
                        </div>
                        <span class="fas fa-quote-right"></span>
                </div>

                <div class="box">
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti asperiores
                        laboriosam praesentium enim maiores? Ad repellat voluptates alias facere repudiandae
                        dolor accusamus enim ut odit, aliquam nesciunt esque nulla dignissimos.</p>
                        <div class="user">
                            <img src="images/flor2.jpeg" alt="">
                            <div class="user-info">
                                <h3>john deo</h3>
                             
                            </div>
                        </div>
                        <span class="fas fa-quote-right"></span>
                </div>

                <div class="box">
                    <div class="stars">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Corrupti asperiores
                        laboriosam praesentium enim maiores? Ad repellat voluptates alias facere repudiandae
                        dolor accusamus enim ut odit, aliquam nesciunt esque nulla dignissimos.</p>
                        <div class="user">
                            <img src="images/flor2.jpeg" alt="">
                            <div class="user-info">
                                <h3>john deo</h3>
                              
                            </div>
                        </div>
                        <span class="fas fa-quote-right"></span>
                </div>
          </div>
        </section>

        <section class="contacts" id="contacts">
            <h1 class="heading">  Entre em <span> contato </span>  </h1>
               
            <div class="row">
                <form action="">
                    <input type="text" placeholder="Nome" class="box">
                    <input type="email" placeholder="E-mail" class="box">
                    <input type="number" placeholder="Número" class="box">
                    <textarea name="" class="box" placeholder="Menssagem" id="" cols="30" rows="10"></textarea>
                    <input type="submit" value="Enviar menssagem" class="btn">
                </form>

                    <div class="image">
                        <img src="images/regando4.webp" alt="">
                    </div>
            </div>
        </section>

        <section class="footer">
            <div class="box-container">
                <div class="box">
                    <h3>Links rápidos</h3>
                    <a href="#">home</a>
                    <a href="#">Sobre</a>
                    <a href="#">Produtos</a>
                    <a href="#">Avaliação</a>
                    <a href="#">Contato</a>
                </div>

                <div class="box">
                    <h3>Links extras</h3>
                    <a href="#">Minha conta</a>
                    <a href="#">Meus pedidos</a>
                    <a href="#">Meus favoritos</a>
                </div>

                <div class="box">
                    <h3>locations</h3>
                    <a href="#">Brasil</a>
                    <a href="#">USA</a>
                    <a href="#">Japão</a>
                    <a href="#">Espanha</a>
                </div>

                <div class="box">
                    <h3>Informações de contato</h3>
                    <a href="#">(14)99562-3658</a>
                    <a href="#">example@gmail.com.br</a>
                    <a href="#">São Paulo, Brasil - 17404910</a>
                    <img src="images/pagamento.png" alt="">
                </div>
            </div>

            <div class="credit"> Criado por <span> Ana A. </span> | direitos autorais reservados</div>       

        </section>

    
</body>
</html>
